# Site settings
title: Tarkaa's Cabin
description: Pieces of ideas, sometimes may write diaries.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/Tarkaa/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://samanyougarg.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: Tarkaa #github username
repo: Tarkaa.github.io #github repository
branch: master #branch
relative_source: ./_pages #source directory
destination: .／_pages #destination directory
production_url:  https://Tarkaa.github.io/
source_url:  https://github.com/Tarkaa/Tarkaa.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml